NIFTY50_SYMBOLS = [
    "RELIANCE", "TCS", "HDFCBANK", "BHARTIARTL", "ICICIBANK",
    "INFOSYS", "SBIN", "HINDUNILVR", "ITC", "LT",
    "KOTAKBANK", "HCLTECH", "MARUTI", "AXISBANK", "ASIANPAINT",
    "BAJFINANCE", "NTPC", "ONGC", "POWERGRID", "ULTRACEMCO",
    "WIPRO", "M&M", "NESTLEIND", "TITAN", "ADANIENT",
    "ADANIPORTS", "COALINDIA", "BAJAJFINSV", "SUNPHARMA", "TATAMOTORS",
    "TATASTEEL", "TECHM", "GRASIM", "INDUSINDBK", "HINDALCO",
    "JSWSTEEL", "BPCL", "DRREDDY", "CIPLA", "EICHERMOT",
    "BRITANNIA", "DIVISLAB", "APOLLOHOSP", "TATACONSUM", "HEROMOTOCO",
    "SHRIRAMFIN", "BAJAJ-AUTO", "HDFCLIFE", "SBILIFE", "BEL"
]

# NSE exchange segment for Upstox
NSE_SEGMENT = "NSE_EQ"

# Candle intervals
INTERVAL_5MIN = "5minute"
INTERVAL_DAY = "1day"
