"""add signal_features table

Revision ID: cd1cca3a9c58
Revises: a3a08a787ece
Create Date: 2026-05-09 13:52:07.594431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1cca3a9c58'
down_revision: Union[str, Sequence[str], None] = 'a3a08a787ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_features_symbol_timestamp', 'signal_features', ['symbol', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_features_symbol_timestamp', table_name='signal_features')
    op.drop_table('signal_features')
    # ### end Alembic commands ###
